# Generated by Django 5.2.7 on 2025-11-01 13:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('structural', 'Structural Materials'), ('finishing', 'Finishing Materials'), ('electrical', 'Electrical Supplies'), ('plumbing', 'Plumbing Supplies'), ('roofing', 'Roofing Materials'), ('flooring', 'Flooring Materials'), ('paint', 'Paint & Coatings'), ('hardware', 'Hardware'), ('other', 'Other')], max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bag', 'Bag'), ('ton', 'Ton'), ('sqm', 'Square Meter'), ('sqft', 'Square Foot'), ('piece', 'Piece'), ('liter', 'Liter'), ('gallon', 'Gallon'), ('meter', 'Meter'), ('foot', 'Foot'), ('bundle', 'Bundle'), ('box', 'Box')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('api', 'API Integration'), ('scraper', 'Web Scraper')], default='manual', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='materials.material')),
            ],
            options={
                'db_table': 'material_prices',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('above', 'Price Above Threshold'), ('below', 'Price Below Threshold'), ('change', 'Price Change Percentage')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='materials.material')),
            ],
            options={
                'db_table': 'price_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
