# Generated by Django 5.2.7 on 2025-11-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialprice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_prices', to='materials.supplier'),
        ),
        migrations.AddIndex(
            model_name='materialprice',
            index=models.Index(fields=['material', '-recorded_at'], name='material_pr_materia_d579ff_idx'),
        ),
        migrations.AddIndex(
            model_name='materialprice',
            index=models.Index(fields=['recorded_at'], name='material_pr_recorde_cbfc6e_idx'),
        ),
    ]
