# Generated by Django 5.2.7 on 2025-11-14 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About RIVERHEDGE PARTNERS LIMITED', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline or subtitle', max_length=300)),
                ('company_description', models.TextField(default='RIVERHEDGE PARTNERS LIMITED is a leading real estate company...', help_text='Main description of the company')),
                ('mission', models.TextField(blank=True, help_text='Company mission statement')),
                ('vision', models.TextField(blank=True, help_text='Company vision statement')),
                ('core_values', models.TextField(blank=True, help_text='Enter core values, one per line')),
                ('services', models.TextField(blank=True, help_text='Enter services offered, one per line')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('twitter_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('instagram_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('why_choose_us', models.TextField(blank=True, help_text='Why customers should choose your company')),
                ('team_description', models.TextField(blank=True, help_text='Description of your team')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years in business')),
                ('properties_sold', models.IntegerField(default=0, help_text='Total properties sold')),
                ('happy_clients', models.IntegerField(default=0, help_text='Number of satisfied clients')),
                ('team_members', models.IntegerField(default=0, help_text='Number of team members')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
