# Generated by Django 5.2.7 on 2025-11-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('price_trends', 'Price Trends'), ('sales_performance', 'Sales Performance'), ('market_analysis', 'Market Analysis'), ('commission', 'Commission Report'), ('inventory', 'Inventory Report'), ('custom', 'Custom Report')], max_length=30)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
