# Generated by Django 5.2.7 on 2025-11-17 11:55

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('property_deed', 'Property Deed'), ('property_contract', 'Property Contract'), ('property_certificate', 'Property Certificate'), ('property_inspection', 'Inspection Report'), ('property_appraisal', 'Appraisal Report'), ('property_survey', 'Survey Report'), ('property_title', 'Title Document'), ('transaction_agreement', 'Transaction Agreement'), ('transaction_receipt', 'Receipt'), ('transaction_invoice', 'Invoice'), ('transaction_contract', 'Contract'), ('transaction_disclosure', 'Disclosure Document'), ('identification', 'Identification'), ('financial', 'Financial Document'), ('legal', 'Legal Document'), ('other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[('property', 'Property'), ('transaction', 'Transaction'), ('user', 'User'), ('general', 'General')], max_length=20)),
                ('file', models.FileField(upload_to=documents.models.get_upload_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_documents', to='properties.property')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.transaction')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category', '-uploaded_at'], name='documents_categor_a8013d_idx'), models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'), models.Index(fields=['related_property', '-uploaded_at'], name='documents_related_876f7c_idx'), models.Index(fields=['related_transaction', '-uploaded_at'], name='documents_related_21d817_idx'), models.Index(fields=['related_user', '-uploaded_at'], name='documents_related_21f06b_idx')],
            },
        ),
    ]
