# Generated by Django 5.2.7 on 2025-11-17 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('appointment_type', models.CharField(choices=[('property_viewing', 'Property Viewing'), ('meeting', 'Meeting'), ('consultation', 'Consultation'), ('inspection', 'Property Inspection'), ('signing', 'Document Signing'), ('other', 'Other')], default='meeting', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Online meeting link (Zoom, Teams, etc.)', null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes visible to client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent handling the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='agent_appointments', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Additional attendees', related_name='appointments_attending', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, help_text='Client attending the appointment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='properties.property')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='properties.transaction')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='appointment_start_t_d798d8_idx'), models.Index(fields=['agent', 'start_time'], name='appointment_agent_i_68179d_idx'), models.Index(fields=['client', 'start_time'], name='appointment_client__63cb01_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['appointment_type'], name='appointment_appoint_6f2f79_idx')],
            },
        ),
    ]
