# Generated by Django 5.2.7 on 2025-11-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost_estimates', '0002_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costestimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cost_estimates.costestimate'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
